/**
 * License Key E2E Tests
 *
 * Validates the full license key lifecycle:
 *   - Generate → Validate (HMAC roundtrip)
 *   - Developer/demo keys
 *   - Expired keys
 *   - Invalid/malformed keys
 *   - Input normalization and formatting
 */

import { describe, it, expect } from 'vitest'
import {
  validateLicenseKey,
  normalizeKeyInput,
  formatKeyForDisplay,
  isTypingDevKey,
} from '../../../shared/utils/license'

// ── Roundtrip: Verify keys generated by generate-license-keys.mjs ──

describe('License Key Validation — Roundtrip', () => {
  // These keys were generated with scripts/generate-license-keys.mjs
  // using the POKERGTO_LICENSE_SECRET from .env
  it('validates a Pro key (12-month expiry)', async () => {
    const result = await validateLicenseKey('PGTO-0019-731M-3RWY')
    expect(result.valid).toBe(true)
    expect(result.tier).toBe('pro')
    expect(result.expiry).toBeDefined()
  })

  it('validates a Lifetime key', async () => {
    const result = await validateLicenseKey('PGTO-01W4-VH6Y-W3MT')
    expect(result.valid).toBe(true)
    expect(result.tier).toBe('lifetime')
  })

  it('rejects a key with wrong signature', async () => {
    const result = await validateLicenseKey('PGTO-0000-0000-0000')
    expect(result.valid).toBe(false)
    expect(result.message).toContain('签名验证失败')
  })

  it('rejects a key that is too short', async () => {
    const result = await validateLicenseKey('PGTO-1234')
    expect(result.valid).toBe(false)
  })
})

// ── Developer / Demo Keys ──

describe('Developer and Demo Keys', () => {
  it('activates developer mode with PGTO-DEV-ADMIN-KEY', async () => {
    const result = await validateLicenseKey('PGTO-DEV-ADMIN-KEY')
    expect(result.valid).toBe(true)
    expect(result.tier).toBe('developer')
  })

  it('activates developer mode with raw dev key', async () => {
    const result = await validateLicenseKey('PGTODEVADMINKEY')
    expect(result.valid).toBe(true)
    expect(result.tier).toBe('developer')
  })

  it('activates demo pro key', async () => {
    const result = await validateLicenseKey('PGTO-DEMO-PRO-KEY')
    expect(result.valid).toBe(true)
    expect(result.tier).toBe('pro')
  })

  it('activates demo lifetime key', async () => {
    const result = await validateLicenseKey('PGTO-DEMO-LIFE-KEY')
    expect(result.valid).toBe(true)
    expect(result.tier).toBe('lifetime')
  })
})

// ── Input Handling ──

describe('License Key Input Handling', () => {
  it('normalizes lower case input', () => {
    expect(normalizeKeyInput('pgto-0019-731m-3rwy')).toBe('PGTO0019731M3RWY')
  })

  it('formats a key for display', () => {
    const formatted = formatKeyForDisplay('PGTO0019731M3RWY')
    expect(formatted).toBe('PGTO-0019-731M-3RWY')
  })

  it('detects typing of developer key', () => {
    expect(isTypingDevKey('PGTODEV')).toBe(true)
    expect(isTypingDevKey('PGTOPRO')).toBe(false)
  })

  it('rejects keys with invalid characters', async () => {
    const result = await validateLicenseKey('PGTO-!!!!-!!!!-!!!!')
    expect(result.valid).toBe(false)
  })
})

// ── Edge Cases ──

describe('License Validation Edge Cases', () => {
  it('handles empty string', async () => {
    const result = await validateLicenseKey('')
    expect(result.valid).toBe(false)
  })

  it('handles whitespace', async () => {
    const result = await validateLicenseKey('   ')
    expect(result.valid).toBe(false)
  })

  it('handles key with extra dashes and spacing', async () => {
    const result = await validateLicenseKey('  PGTO-0019-731M-3RWY  ')
    // After normalization, should be valid
    expect(result.valid).toBe(true)
    expect(result.tier).toBe('pro')
  })
})
