"""Daily briefing generator — aggregates system status, news, calendar, and insights."""

import logging
from datetime import datetime

from services.llm.client import llm_client
from config import settings

logger = logging.getLogger(__name__)


async def generate_briefing(
    include_system: bool = True,
    include_news: bool = False,
) -> str:
    """Generate a daily briefing summary.

    Args:
        include_system: Include system health check
        include_news: Include news headlines (requires search)

    Returns:
        Formatted markdown briefing
    """
    now = datetime.now()
    sections = []

    # Header
    sections.append(f"# J.A.R.V.I.S. Daily Briefing\n")
    sections.append(f"**{now.strftime('%A, %B %d, %Y')}** | {now.strftime('%H:%M')}\n")

    # System Health
    if include_system:
        try:
            from services.proactive.monitor import check_system_health, check_network

            health = await check_system_health()
            network = await check_network()

            sections.append("## System Status\n")
            sections.append(f"• **Status**: {'🟢 Healthy' if health['status'] == 'healthy' else '⚠️ Warning'}")
            if health.get("cpu_percent") is not None:
                sections.append(f"• **CPU**: {health['cpu_percent']}%")
            if health.get("memory_percent") is not None:
                sections.append(f"• **Memory**: {health['memory_percent']}%")
            if health.get("disk_percent") is not None:
                sections.append(f"• **Disk**: {health['disk_percent']}%")
            if network["connected"]:
                sections.append(f"• **Network**: Connected ({network.get('latency_ms', '?')}ms to 8.8.8.8)")
            else:
                sections.append("• **Network**: ⚠️ Disconnected")

            if health.get("alerts"):
                sections.append("\n### ⚠️ Alerts\n")
                for alert in health["alerts"]:
                    sections.append(f"• {alert}")

            sections.append("")

        except Exception as e:
            logger.warning(f"System health check failed: {e}")
            sections.append("## System Status\n")
            sections.append("• Status: Unable to retrieve\n")

    # AI-generated insights
    sections.append("## Today's Overview\n")
    try:
        prompt = f"""Generate a brief, professional daily briefing opening for {now.strftime('%A, %B %d, %Y')}.
        It's currently {now.strftime('%H:%M')}.
        Be concise (2-3 sentences), British butler tone. Start with "Good morning, sir."
        Mention that proactive monitoring is active and all systems are being watched."""

        result = await llm_client.chat(
            messages=[{"role": "user", "content": prompt}],
            model=settings.fast_model,
            temperature=0.7,
            max_tokens=200,
        )
        sections.append(result["text"])
    except Exception:
        sections.append("Good morning, sir. All systems are operational. I'll alert you if anything requires your attention.\n")

    sections.append("")
    sections.append("---")
    sections.append(f"*Generated by J.A.R.V.I.S. at {now.strftime('%H:%M')}*")

    return "\n".join(sections)
