"""Report generator — produces structured markdown reports from research results."""

import logging
from datetime import datetime

from services.llm.client import llm_client
from config import settings

logger = logging.getLogger(__name__)


async def generate_report(
    query: str,
    search_results: list[dict],
    validation: dict,
    include_citations: bool = True,
) -> str:
    """Generate a structured research report.

    Uses LLM to synthesize search results into a coherent report
    with citations and credibility indicators.
    """

    # Build context from search results
    sources_text = ""
    for i, r in enumerate(search_results):
        sources_text += f"\n[{i+1}] **{r['title']}**\n"
        sources_text += f"    URL: {r['url']}\n"
        sources_text += f"    Summary: {r['snippet']}\n"
        if include_citations:
            sources_text += f"    Source: {r['source']}\n"

    report_prompt = f"""You are J.A.R.V.I.S., generating a research report for your user.

RESEARCH QUERY: {query}

SEARCH RESULTS ({len(search_results)} sources found):
{sources_text}

VALIDATION:
- Reliability: {validation.get('reliability', 'unknown')}
- Agreement score: {validation.get('agreement_score', 0)}
- Sources checked: {validation.get('sources_checked', 0)}

Generate a structured research report with:

1. **Executive Summary** (2-3 sentences)
2. **Key Findings** (5-7 bullet points with source citations [1], [2], etc.)
3. **Detailed Analysis** (thematic sections with headers)
4. **Source Reliability Assessment** (brief table)
5. **Limitations & Gaps** (what's missing, what needs further research)
6. **Next Steps** (recommended follow-up actions)

Format in markdown. Be precise and cite sources when making claims."""

    try:
        result = await llm_client.chat(
            messages=[{"role": "user", "content": report_prompt}],
            model=settings.default_model,
            temperature=0.4,
            max_tokens=4096,
        )

        report = result["text"]

        # Append source list
        if include_citations:
            report += "\n\n---\n\n## Sources\n\n"
            for i, r in enumerate(search_results):
                report += f"[{i+1}] [{r['title']}]({r['url']}) — *{r['source']}*\n"

        report += f"\n\n---\n\n*Report generated by J.A.R.V.I.S. on {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC*"

        return report

    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        # Fallback: simple listing
        fallback = f"# Research: {query}\n\n"
        fallback += f"*{len(search_results)} sources found. AI synthesis unavailable.*\n\n"
        for i, r in enumerate(search_results):
            fallback += f"### [{i+1}] {r['title']}\n"
            fallback += f"{r['snippet']}\n"
            fallback += f"Link: {r['url']}\n\n"
        return fallback
